# Generated by Django 3.1.2 on 2020-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id_tweet', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Who sent the content?', max_length=15)),
                ('tweet_content', models.CharField(help_text='Tweet Content', max_length=280)),
                ('tweet_location', models.CharField(help_text='Location of  the tweet', max_length=20)),
            ],
        ),
    ]
